/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package structs;

import java.util.HashMap;

/**
 * A wrapper class that provides data structures containing language info according to ISO-639.
 */
public class LanguageCodes {
    private static final String[][] LANGUAGE_NAMES_AND_CODES = {
        {"Abkhazian", "abk"},
        {"Achinese", "ace"},
        {"Acoli", "ach"},
        {"Adangme", "ada"},
        {"Adyghe", "ady"},
        {"Afar", "aar"},
        {"Afrikaans", "afr"},
        {"Ainu", "ain"},
        {"Akan", "aka"},
        {"Albanian", "sqi"},
        {"Aleut", "ale"},
        {"Amharic", "amh"},
        {"Angika", "anp"},
        {"Arabic", "ara"},
        {"Aragonese", "arg"},
        {"Arapaho", "arp"},
        {"Arawak", "arw"},
        {"Armenian", "hye"},
        {"Aromanian; Arumanian", "rup"},
        {"Assamese", "asm"},
        {"Asturian; Leonese", "ast"},
        {"Avaric", "ava"},
        {"Awadhi", "awa"},
        {"Aymara", "aym"},
        {"Azerbaijani", "aze"},
        {"Balinese", "ban"},
        {"Baluchi", "bal"},
        {"Bambara", "bam"},
        {"Basa", "bas"},
        {"Bashkir", "bak"},
        {"Basque", "eus"},
        {"Beja; Bedawiyet", "bej"},
        {"Belarusian", "bel"},
        {"Bemba", "bem"},
        {"Bengali", "ben"},
        {"Bhojpuri", "bho"},
        {"Bikol", "bik"},
        {"Bini; Edo", "bin"},
        {"Bislama", "bis"},
        {"Blin; Bilin", "byn"},
        {"Bosnian", "bos"},
        {"Braj", "bra"},
        {"Breton", "bre"},
        {"Buginese", "bug"},
        {"Bulgarian", "bul"},
        {"Buriat", "bua"},
        {"Burmese", "mya"},
        {"Caddo", "cad"},
        {"Catalan; Valencian", "cat"},
        {"Cebuano", "ceb"},
        {"Central Khmer", "khm"},
        {"Chamorro", "cha"},
        {"Chechen", "che"},
        {"Cherokee", "chr"},
        {"Cheyenne", "chy"},
        {"Chichewa; Nyanja", "nya"},
        {"Chinese", "zho"},
        {"Chinook jargon", "chn"},
        {"Chipewyan; Dene Suline", "chp"},
        {"Choctaw", "cho"},
        {"Chuukese", "chk"},
        {"Chuvash", "chv"},
        {"Cornish", "cor"},
        {"Corsican", "cos"},
        {"Cree", "cre"},
        {"Creek", "mus"},
        {"Crimean Tatar", "crh"},
        {"Croatian", "hrv"},
        {"Czech", "ces"},
        {"Dakota", "dak"},
        {"Danish", "dan"},
        {"Dargwa", "dar"},
        {"Delaware", "del"},
        {"Dhivehi; Maldivian", "div"},
        {"Dinka", "din"},
        {"Dogri", "doi"},
        {"Dogrib", "dgr"},
        {"Duala", "dua"},
        {"Dutch; Flemish", "nld"},
        {"Dyula", "dyu"},
        {"Dzongkha", "dzo"},
        {"Eastern Frisian", "frs"},
        {"Efik", "efi"},
        {"Ekajuk", "eka"},
        {"English", "eng"},
        {"Erzya", "myv"},
        {"Estonian", "est"},
        {"Ewe", "ewe"},
        {"Ewondo", "ewo"},
        {"Fang", "fan"},
        {"Fanti", "fat"},
        {"Faroese", "fao"},
        {"Fijian", "fij"},
        {"Filipino; Pilipino", "fil"},
        {"Finnish", "fin"},
        {"Fon", "fon"},
        {"French", "fra"},
        {"Friulian", "fur"},
        {"Fulah", "ful"},
        {"Ga", "gaa"},
        {"Galibi Carib", "car"},
        {"Galician", "glg"},
        {"Ganda", "lug"},
        {"Gayo", "gay"},
        {"Gbaya", "gba"},
        {"Georgian", "kat"},
        {"German", "deu"},
        {"Gilbertese", "gil"},
        {"Gondi", "gon"},
        {"Gorontalo", "gor"},
        {"Grebo", "grb"},
        {"Greek", "ell"},
        {"Guarani", "grn"},
        {"Gujarati", "guj"},
        {"Gwich'in", "gwi"},
        {"Haida", "hai"},
        {"Haitian Creole", "hat"},
        {"Hausa", "hau"},
        {"Hawaiian", "haw"},
        {"Hebrew", "heb"},
        {"Herero", "her"},
        {"Hiligaynon", "hil"},
        {"Hindi", "hin"},
        {"Hiri Motu", "hmo"},
        {"Hmong; Mong", "hmn"},
        {"Hungarian", "hun"},
        {"Hupa", "hup"},
        {"Iban", "iba"},
        {"Icelandic", "isl"},
        {"Igbo", "ibo"},
        {"Iloko", "ilo"},
        {"Inari Sami", "smn"},
        {"Indonesian", "ind"},
        {"Ingush", "inh"},
        {"Inuktitut", "iku"},
        {"Inupiaq", "ipk"},
        {"Irish", "gle"},
        {"Italian", "ita"},
        {"Japanese", "jpn"},
        {"Javanese", "jav"},
        {"Judeo-Arabic", "jrb"},
        {"Judeo-Persian", "jpr"},
        {"Kabardian", "kbd"},
        {"Kabyle", "kab"},
        {"Kachin; Jingpho", "kac"},
        {"Kalaallisut; Greenlandic", "kal"},
        {"Kalmyk; Oirat", "xal"},
        {"Kamba", "kam"},
        {"Kannada", "kan"},
        {"Kanuri", "kau"},
        {"Kara-Kalpak", "kaa"},
        {"Karachay-Balkar", "krc"},
        {"Karelian", "krl"},
        {"Kashmiri", "kas"},
        {"Kashubian", "csb"},
        {"Kazakh", "kaz"},
        {"Khasi", "kha"},
        {"Kikuyu; Gikuyu", "kik"},
        {"Kimbundu", "kmb"},
        {"Kinyarwanda", "kin"},
        {"Kirghiz; Kyrgyz", "kir"},
        {"Komi", "kom"},
        {"Kongo", "kon"},
        {"Konkani", "kok"},
        {"Korean", "kor"},
        {"Kosraean", "kos"},
        {"Kpelle", "kpe"},
        {"Kuanyama; Kwanyama", "kua"},
        {"Kumyk", "kum"},
        {"Kurdish", "kur"},
        {"Kurukh", "kru"},
        {"Kutenai", "kut"},
        {"Ladino", "lad"},
        {"Lahnda", "lah"},
        {"Lamba", "lam"},
        {"Lao", "lao"},
        {"Latvian", "lav"},
        {"Lezghian", "lez"},
        {"Limburgan; Limburgish", "lim"},
        {"Lingala", "lin"},
        {"Lithuanian", "lit"},
        {"Low German; Low Saxon", "nds"},
        {"Lower Sorbian", "dsb"},
        {"Lozi", "loz"},
        {"Luba-Katanga", "lub"},
        {"Luba-Lulua", "lua"},
        {"Lule Sami", "smj"},
        {"Lunda", "lun"},
        {"Luo (Kenya and Tanzania)", "luo"},
        {"Lushai", "lus"},
        {"Luxembourgish", "ltz"},
        {"Macedonian", "mkd"},
        {"Madurese", "mad"},
        {"Magahi", "mag"},
        {"Maithili", "mai"},
        {"Makasar", "mak"},
        {"Malagasy", "mlg"},
        {"Malay", "msa"},
        {"Malayalam", "mal"},
        {"Maltese", "mlt"},
        {"Manchu", "mnc"},
        {"Mandar", "mdr"},
        {"Mandingo", "man"},
        {"Manipuri", "mni"},
        {"Manx", "glv"},
        {"Maori", "mri"},
        {"Mapudungun; Mapuche", "arn"},
        {"Marathi", "mar"},
        {"Mari", "chm"},
        {"Marshallese", "mah"},
        {"Marwari", "mwr"},
        {"Masai", "mas"},
        {"Mende", "men"},
        {"Mi'kmaq; Micmac", "mic"},
        {"Minangkabau", "min"},
        {"Mirandese", "mwl"},
        {"Mohawk", "moh"},
        {"Moksha", "mdf"},
        {"Mongo", "lol"},
        {"Mongolian", "mon"},
        {"Montenegrin", "cnr"},
        {"Mossi", "mos"},
        {"N'Ko", "nqo"},
        {"Nauru", "nau"},
        {"Navajo; Navaho", "nav"},
        {"Ndebele, North", "nde"},
        {"Ndebele, South", "nbl"},
        {"Ndonga", "ndo"},
        {"Neapolitan", "nap"},
        {"Nepal Bhasa; Newari", "new"},
        {"Nepali", "nep"},
        {"Nias", "nia"},
        {"Niuean", "niu"},
        {"Nogai", "nog"},
        {"Northern Frisian", "frr"},
        {"Northern Sami", "sme"},
        {"Northern Sotho; Sepedi", "nso"},
        {"Norwegian", "nor"},
        {"Norwegian Bokmål", "nob"},
        {"Norwegian Nynorsk", "nno"},
        {"Nyamwezi", "nym"},
        {"Nyankole", "nyn"},
        {"Nyoro", "nyo"},
        {"Nzima", "nzi"},
        {"Occitan; Provençal", "oci"},
        {"Ojibwa", "oji"},
        {"Oriya", "ori"},
        {"Oromo", "orm"},
        {"Osage", "osa"},
        {"Ossetian; Ossetic", "oss"},
        {"Palauan", "pau"},
        {"Pampanga; Kapampangan", "pam"},
        {"Pangasinan", "pag"},
        {"Panjabi; Punjabi", "pan"},
        {"Papiamento", "pap"},
        {"Persian", "fas"},
        {"Pohnpeian", "pon"},
        {"Polish", "pol"},
        {"Portuguese", "por"},
        {"Pushto; Pashto", "pus"},
        {"Quechua", "que"},
        {"Rajasthani", "raj"},
        {"Rapanui", "rap"},
        {"Rarotongan", "rar"},
        {"Romanian; Moldovan", "ron"},
        {"Romansh", "roh"},
        {"Romany", "rom"},
        {"Rundi", "run"},
        {"Russian", "rus"},
        {"Samoan", "smo"},
        {"Sandawe", "sad"},
        {"Sango", "sag"},
        {"Santali", "sat"},
        {"Sardinian", "srd"},
        {"Sasak", "sas"},
        {"Scots", "sco"},
        {"Scottish Gaelic", "gla"},
        {"Selkup", "sel"},
        {"Serbian", "srp"},
        {"Serer", "srr"},
        {"Shan", "shn"},
        {"Shona", "sna"},
        {"Sichuan Yi; Nuosu", "iii"},
        {"Sicilian", "scn"},
        {"Sidamo", "sid"},
        {"Siksika", "bla"},
        {"Sindhi", "snd"},
        {"Sinhala; Sinhalese", "sin"},
        {"Skolt Sami", "sms"},
        {"Slave (Athapascan)", "den"},
        {"Slovak", "slk"},
        {"Slovenian", "slv"},
        {"Somali", "som"},
        {"Soninke", "snk"},
        {"Sotho, Southern", "sot"},
        {"Southern Altai", "alt"},
        {"Southern Sami", "sma"},
        {"Spanish; Castilian", "spa"},
        {"Sranan Tongo", "srn"},
        {"Standard Moroccan Tamazight", "zgh"},
        {"Sukuma", "suk"},
        {"Sundanese", "sun"},
        {"Susu", "sus"},
        {"Swahili", "swa"},
        {"Swati", "ssw"},
        {"Swedish", "swe"},
        {"Swiss German; Alemannic; Alsatian", "gsw"},
        {"Syriac", "syr"},
        {"Tagalog", "tgl"},
        {"Tahitian", "tah"},
        {"Tajik", "tgk"},
        {"Tamashek", "tmh"},
        {"Tamil", "tam"},
        {"Tatar", "tat"},
        {"Telugu", "tel"},
        {"Tereno", "ter"},
        {"Tetum", "tet"},
        {"Thai", "tha"},
        {"Tibetan", "bod"},
        {"Tigre", "tig"},
        {"Tigrinya", "tir"},
        {"Timne", "tem"},
        {"Tiv", "tiv"},
        {"Tlingit", "tli"},
        {"Tok Pisin", "tpi"},
        {"Tokelau", "tkl"},
        {"Tonga (Nyasa)", "tog"},
        {"Tonga (Tonga Islands)", "ton"},
        {"Tsimshian", "tsi"},
        {"Tsonga", "tso"},
        {"Tswana", "tsn"},
        {"Tumbuka", "tum"},
        {"Turkish", "tur"},
        {"Turkmen", "tuk"},
        {"Tuvalu", "tvl"},
        {"Tuvinian", "tyv"},
        {"Twi", "twi"},
        {"Udmurt", "udm"},
        {"Uighur; Uyghur", "uig"},
        {"Ukrainian", "ukr"},
        {"Umbundu", "umb"},
        {"Upper Sorbian", "hsb"},
        {"Urdu", "urd"},
        {"Uzbek", "uzb"},
        {"Vai", "vai"},
        {"Venda", "ven"},
        {"Vietnamese", "vie"},
        {"Votic", "vot"},
        {"Walloon", "wln"},
        {"Waray", "war"},
        {"Washo", "was"},
        {"Welsh", "cym"},
        {"Western Frisian", "fry"},
        {"Wolaitta; Wolaytta", "wal"},
        {"Wolof", "wol"},
        {"Xhosa", "xho"},
        {"Yakut", "sah"},
        {"Yao", "yao"},
        {"Yapese", "yap"},
        {"Yiddish", "yid"},
        {"Yoruba", "yor"},
        {"Zapotec", "zap"},
        {"Zaza; Dimli; Kirdki; Kirmanjki; Zazaki", "zza"},
        {"Zenaga", "zen"},
        {"Zhuang; Chuang", "zha"},
        {"Zulu", "zul"},
        {"Zuni", "zun"}
    };

    // A list including every language's name.
    public static final String[] LANGUAGES_NAMES = getLanguagesNames();
    // A HashMap mapping language names to the associated 3-letter codes.
    public static final HashMap<String, String> LANGUAGE_NAMES_TO_CODES_MAP = getLanguageNamesToCodesMap();

    /**
     * Constructs a list including every language's name.
     * @return The list of language names.
     */
    private static String[] getLanguagesNames() {
        int numberOfLanguages = LANGUAGE_NAMES_AND_CODES.length;
        String[] languagesNames = new String[numberOfLanguages];
        for (int i = 0; i < numberOfLanguages; i++) {
            languagesNames[i] = LANGUAGE_NAMES_AND_CODES[i][0];
        }
        return languagesNames;
    }


    /**
     * Constructs a HashMap with language names as keys and 3-letter language codes as values.
     * @return The HashMap mapping language names to language codes.
     */
    private static HashMap<String, String> getLanguageNamesToCodesMap() {
        HashMap<String, String> languageNamesToCodesMap = new HashMap<>();
        for (String[] languageNameAndCode : LANGUAGE_NAMES_AND_CODES) {
            String languageName = languageNameAndCode[0];
            String languageCode = languageNameAndCode[1];
            languageNamesToCodesMap.put(languageName, languageCode);
        }
        return languageNamesToCodesMap;
    }
}
